---
apiVersion: compute.azure.crossplane.io/v1alpha3
kind: AKSCluster
metadata:
  name: akscrossplane
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  resourceGroupNameRef:
    name: rg-crossplane
  vnetSubnetIDRef:
    name: sub-crossplane
  location: eastus
  version: "1.30.4"
  nodeCount: 1
  nodeVMSize: Standard_B2s
  dnsNamePrefix: crossplane-aks
  disableRBAC: false
  providerConfigRef:
    name: default
  writeConnectionSecretToRef:
    namespace: crossplane
    name: akscrossplane
